use std::collections::HashMap;
use super::CardSpec as CardDef;

mod adaptation;
mod alpha;
mod battlehymn;
mod beta;
mod blasphemy;
mod bowlingbash;
mod brilliance;
mod carvereality;
mod collect;
mod conclude;
mod conjureblade;
mod consecrate;
mod crescendo;
mod crushjoints;
mod cutthroughfate;
mod deceivereality;
mod defend_p;
mod deusexmachina;
mod devaform;
mod devotion;
mod emptybody;
mod emptyfist;
mod emptymind;
mod eruption;
mod establishment;
mod evaluate;
mod expunger;
mod fasting;
mod fearnoevil;
mod flurry;
mod flyingsleeves;
mod followup;
mod foreigninfluence;
mod halt;
mod holywater;
mod indignation;
mod innerpeace;
mod insight;
mod judgement;
mod justlucky;
mod lessonlearned;
mod likewater;
mod masterreality;
mod meditate;
mod mentalfortress;
mod miracle;
mod nirvana;
mod omega;
mod omniscience;
mod perseverance;
mod pray;
mod pressurepoints;
mod prostrate;
mod protect;
mod ragnarok;
mod reachheaven;
mod safety;
mod sanctity;
mod sandsoftime;
mod sashwhip;
mod scrawl;
mod signaturemove;
mod smite;
mod spiritshield;
mod strike_p;
mod study;
mod swivel;
mod talktothehand;
mod tantrum;
mod thirdeye;
mod throughviolence;
mod tranquility;
mod vault;
mod vengeance;
mod vigilance;
mod wallop;
mod waveofthehand;
mod weave;
mod wheelkick;
mod windmillstrike;
mod wireheading;
mod wish;
mod worship;
mod wreathofflame;

pub fn register_watcher(cards: &mut HashMap<&'static str, CardDef>) {
    adaptation::register(cards);
    alpha::register(cards);
    battlehymn::register(cards);
    beta::register(cards);
    blasphemy::register(cards);
    bowlingbash::register(cards);
    brilliance::register(cards);
    carvereality::register(cards);
    collect::register(cards);
    conclude::register(cards);
    conjureblade::register(cards);
    consecrate::register(cards);
    crescendo::register(cards);
    crushjoints::register(cards);
    cutthroughfate::register(cards);
    deceivereality::register(cards);
    defend_p::register(cards);
    deusexmachina::register(cards);
    devaform::register(cards);
    devotion::register(cards);
    emptybody::register(cards);
    emptyfist::register(cards);
    emptymind::register(cards);
    eruption::register(cards);
    establishment::register(cards);
    evaluate::register(cards);
    expunger::register(cards);
    fasting::register(cards);
    fearnoevil::register(cards);
    flurry::register(cards);
    flyingsleeves::register(cards);
    followup::register(cards);
    foreigninfluence::register(cards);
    halt::register(cards);
    holywater::register(cards);
    indignation::register(cards);
    innerpeace::register(cards);
    insight::register(cards);
    judgement::register(cards);
    justlucky::register(cards);
    lessonlearned::register(cards);
    likewater::register(cards);
    masterreality::register(cards);
    meditate::register(cards);
    mentalfortress::register(cards);
    miracle::register(cards);
    nirvana::register(cards);
    omega::register(cards);
    omniscience::register(cards);
    perseverance::register(cards);
    pray::register(cards);
    pressurepoints::register(cards);
    prostrate::register(cards);
    protect::register(cards);
    ragnarok::register(cards);
    reachheaven::register(cards);
    safety::register(cards);
    sanctity::register(cards);
    sandsoftime::register(cards);
    sashwhip::register(cards);
    scrawl::register(cards);
    signaturemove::register(cards);
    smite::register(cards);
    spiritshield::register(cards);
    strike_p::register(cards);
    study::register(cards);
    swivel::register(cards);
    talktothehand::register(cards);
    tantrum::register(cards);
    thirdeye::register(cards);
    throughviolence::register(cards);
    tranquility::register(cards);
    vault::register(cards);
    vengeance::register(cards);
    vigilance::register(cards);
    wallop::register(cards);
    waveofthehand::register(cards);
    weave::register(cards);
    wheelkick::register(cards);
    windmillstrike::register(cards);
    wireheading::register(cards);
    wish::register(cards);
    worship::register(cards);
    wreathofflame::register(cards);
}
