"""
Card Audit Tests: Java vs Python parity for ALL Watcher, Colorless, Curse, Status, and Temp cards.

Generated by auditing every Java card constructor (super() call + field assignments + upgrade())
against Python Card definitions in packages/engine/content/cards.py.

Discrepancies are marked with MISMATCH comments.
"""

import pytest
from packages.engine.content.cards import (
    # Enums
    CardType, CardRarity, CardColor, CardTarget,
    # Watcher Basic
    STRIKE_W, DEFEND_W, ERUPTION, VIGILANCE,
    # Watcher Common Attacks
    BOWLING_BASH, CUT_THROUGH_FATE, EMPTY_FIST, FLURRY_OF_BLOWS,
    FLYING_SLEEVES, FOLLOW_UP, HALT, JUST_LUCKY, PRESSURE_POINTS,
    SASH_WHIP, CONSECRATE, CRUSH_JOINTS,
    # Watcher Common Skills
    TRANQUILITY, CRESCENDO, EMPTY_BODY, EMPTY_MIND, EVALUATE,
    INNER_PEACE, PROTECT, THIRD_EYE, PROSTRATE,
    # Watcher Uncommon Attacks
    TANTRUM, FEAR_NO_EVIL, REACH_HEAVEN, SANDS_OF_TIME,
    SIGNATURE_MOVE, TALK_TO_THE_HAND, WALLOP, WEAVE, WHEEL_KICK,
    WINDMILL_STRIKE, CONCLUDE, CARVE_REALITY,
    # Watcher Uncommon Skills
    COLLECT, DECEIVE_REALITY, INDIGNATION, MEDITATE, PERSEVERANCE,
    PRAY, SANCTITY, SWIVEL, WAVE_OF_THE_HAND, SIMMERING_FURY,
    WORSHIP, WREATH_OF_FLAME,
    # Watcher Uncommon Powers
    BATTLE_HYMN, FASTING, LIKE_WATER, MENTAL_FORTRESS, NIRVANA,
    RUSHDOWN, STUDY,
    # Watcher Rare Attacks
    BRILLIANCE, JUDGMENT, LESSON_LEARNED, RAGNAROK,
    # Watcher Rare Skills
    DEUS_EX_MACHINA, ALPHA, BLASPHEMY, CONJURE_BLADE,
    FOREIGN_INFLUENCE, OMNISCIENCE, SCRAWL, SPIRIT_SHIELD, VAULT, WISH,
    # Watcher Rare Powers
    DEVA_FORM, DEVOTION, ESTABLISHMENT, MASTER_REALITY, FORESIGHT,
    # Temp/Special Cards
    MIRACLE, INSIGHT, SMITE, SAFETY, THROUGH_VIOLENCE, EXPUNGER, BETA, OMEGA,
    # Curse Cards
    ASCENDERS_BANE, CLUMSY, CURSE_OF_THE_BELL, DECAY, DOUBT, INJURY,
    NECRONOMICURSE, NORMALITY, PAIN, PARASITE, PRIDE, REGRET, SHAME, WRITHE,
    # Status Cards
    BURN, DAZED, SLIMED, VOID, WOUND,
    # Registries
    WATCHER_CARDS, COLORLESS_CARDS, CURSE_CARDS, STATUS_CARDS,
)


# ============================================================
# WATCHER BASIC CARDS
# ============================================================

class TestWatcherBasicCards:
    """Tests for Strike_P, Defend_P, Eruption, Vigilance."""

    def test_strike_p(self):
        c = STRIKE_W
        assert c.id == "Strike_P"
        assert c.card_type == CardType.ATTACK
        assert c.rarity == CardRarity.BASIC
        assert c.color == CardColor.PURPLE
        assert c.cost == 1
        assert c.base_damage == 6
        assert c.upgrade_damage == 3

    def test_defend_p(self):
        c = DEFEND_W
        assert c.id == "Defend_P"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.BASIC
        assert c.target == CardTarget.SELF
        assert c.cost == 1
        assert c.base_block == 5
        assert c.upgrade_block == 3

    def test_eruption(self):
        c = ERUPTION
        assert c.id == "Eruption"
        assert c.card_type == CardType.ATTACK
        assert c.rarity == CardRarity.BASIC
        assert c.cost == 2
        assert c.base_damage == 9
        assert c.upgrade_cost == 1  # Upgrade reduces cost to 1

    def test_vigilance(self):
        c = VIGILANCE
        assert c.id == "Vigilance"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.BASIC
        assert c.target == CardTarget.SELF
        assert c.cost == 2
        assert c.base_block == 8
        assert c.upgrade_block == 4


# ============================================================
# WATCHER COMMON ATTACKS
# ============================================================

class TestWatcherCommonAttacks:

    def test_bowling_bash(self):
        c = BOWLING_BASH
        assert c.id == "BowlingBash"
        assert c.card_type == CardType.ATTACK
        assert c.rarity == CardRarity.COMMON
        assert c.cost == 1
        assert c.base_damage == 7
        assert c.upgrade_damage == 3

    def test_cut_through_fate(self):
        c = CUT_THROUGH_FATE
        assert c.id == "CutThroughFate"
        assert c.card_type == CardType.ATTACK
        assert c.rarity == CardRarity.COMMON
        assert c.cost == 1
        assert c.base_damage == 7
        assert c.upgrade_damage == 2
        assert c.base_magic == 2
        assert c.upgrade_magic == 1

    def test_empty_fist(self):
        c = EMPTY_FIST
        assert c.id == "EmptyFist"
        assert c.card_type == CardType.ATTACK
        assert c.rarity == CardRarity.COMMON
        assert c.cost == 1
        assert c.base_damage == 9
        assert c.upgrade_damage == 5
        assert c.exit_stance is True

    def test_flurry_of_blows(self):
        c = FLURRY_OF_BLOWS
        assert c.id == "FlurryOfBlows"
        assert c.card_type == CardType.ATTACK
        assert c.rarity == CardRarity.COMMON
        assert c.cost == 0
        assert c.base_damage == 4
        assert c.upgrade_damage == 2

    def test_flying_sleeves(self):
        c = FLYING_SLEEVES
        assert c.id == "FlyingSleeves"
        assert c.card_type == CardType.ATTACK
        assert c.rarity == CardRarity.COMMON
        assert c.cost == 1
        assert c.base_damage == 4
        assert c.upgrade_damage == 2
        assert c.retain is True  # selfRetain in Java

    def test_follow_up(self):
        c = FOLLOW_UP
        assert c.id == "FollowUp"
        assert c.card_type == CardType.ATTACK
        assert c.rarity == CardRarity.COMMON
        assert c.cost == 1
        assert c.base_damage == 7
        assert c.upgrade_damage == 4

    def test_halt(self):
        """Java: Halt is SKILL, cost=0, baseBlock=3, baseMagicNumber=9, upgradeBlock(1).
        The magic number represents total block in Wrath (base block + 6 + timesUpgraded*4).
        """
        c = HALT
        assert c.id == "Halt"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.COMMON
        assert c.target == CardTarget.SELF
        assert c.cost == 0
        assert c.base_block == 3
        assert c.upgrade_block == 1
        # MISMATCH: Java baseMagicNumber=9 (block 3 + wrath bonus 6), Python doesn't set base_magic to 9
        # The Halt card's magic number is a display value representing total Wrath block.

    def test_just_lucky(self):
        c = JUST_LUCKY
        assert c.id == "JustLucky"
        assert c.card_type == CardType.ATTACK
        assert c.rarity == CardRarity.COMMON
        assert c.cost == 0
        assert c.base_damage == 3
        assert c.upgrade_damage == 1
        assert c.base_block == 2
        assert c.upgrade_block == 1
        assert c.base_magic == 1
        assert c.upgrade_magic == 1

    def test_pressure_points(self):
        c = PRESSURE_POINTS
        assert c.id == "PathToVictory"  # Java ID
        assert c.card_type == CardType.SKILL  # MISMATCH: Python currently has this wrong - it should be SKILL not ATTACK
        assert c.rarity == CardRarity.COMMON
        assert c.cost == 1
        assert c.base_magic == 8
        assert c.upgrade_magic == 3

    def test_sash_whip(self):
        c = SASH_WHIP
        assert c.id == "SashWhip"
        assert c.card_type == CardType.ATTACK
        assert c.rarity == CardRarity.COMMON
        assert c.cost == 1
        assert c.base_damage == 8
        assert c.upgrade_damage == 2
        assert c.base_magic == 1
        assert c.upgrade_magic == 1

    def test_consecrate(self):
        c = CONSECRATE
        assert c.id == "Consecrate"
        assert c.card_type == CardType.ATTACK
        assert c.rarity == CardRarity.COMMON
        assert c.target == CardTarget.ALL_ENEMY
        assert c.cost == 0
        assert c.base_damage == 5
        assert c.upgrade_damage == 3

    def test_crush_joints(self):
        c = CRUSH_JOINTS
        assert c.id == "CrushJoints"
        assert c.card_type == CardType.ATTACK
        assert c.rarity == CardRarity.COMMON
        assert c.cost == 1
        assert c.base_damage == 8
        assert c.upgrade_damage == 2
        assert c.base_magic == 1
        assert c.upgrade_magic == 1


# ============================================================
# WATCHER COMMON SKILLS
# ============================================================

class TestWatcherCommonSkills:

    def test_tranquility(self):
        """Java: cost=1, upgrade reduces cost to 0. exhaust=true, selfRetain=true."""
        c = TRANQUILITY
        assert c.id == "ClearTheMind"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.COMMON
        assert c.target == CardTarget.SELF
        # MISMATCH: Java base cost is 1, upgraded to 0. Python has cost=0 (wrong base).
        assert c.cost == 1, f"MISMATCH: Java cost=1, Python cost={c.cost}"
        assert c.upgrade_cost == 0, "Upgrade should set cost to 0"
        assert c.exhaust is True
        assert c.retain is True

    def test_crescendo(self):
        """Java: cost=1, upgrade reduces cost to 0. exhaust=true, selfRetain=true."""
        c = CRESCENDO
        assert c.id == "Crescendo"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.COMMON
        assert c.target == CardTarget.SELF
        # MISMATCH: Java base cost is 1, upgraded to 0. Python has cost=0 (wrong base).
        assert c.cost == 1, f"MISMATCH: Java cost=1, Python cost={c.cost}"
        assert c.upgrade_cost == 0, "Upgrade should set cost to 0"
        assert c.exhaust is True
        assert c.retain is True

    def test_empty_body(self):
        c = EMPTY_BODY
        assert c.id == "EmptyBody"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.COMMON
        assert c.cost == 1
        assert c.base_block == 7
        assert c.upgrade_block == 3
        assert c.exit_stance is True

    def test_empty_mind(self):
        c = EMPTY_MIND
        assert c.id == "EmptyMind"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.UNCOMMON  # Java says UNCOMMON
        assert c.cost == 1
        assert c.base_magic == 2
        assert c.upgrade_magic == 1
        assert c.exit_stance is True

    def test_evaluate(self):
        c = EVALUATE
        assert c.id == "Evaluate"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.COMMON
        assert c.cost == 1
        assert c.base_block == 6
        assert c.upgrade_block == 4

    def test_inner_peace(self):
        c = INNER_PEACE
        assert c.id == "InnerPeace"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.UNCOMMON  # Java says UNCOMMON
        assert c.cost == 1
        assert c.base_magic == 3
        assert c.upgrade_magic == 1

    def test_protect(self):
        c = PROTECT
        assert c.id == "Protect"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.COMMON
        assert c.cost == 2
        assert c.base_block == 12
        assert c.upgrade_block == 4
        assert c.retain is True

    def test_third_eye(self):
        c = THIRD_EYE
        assert c.id == "ThirdEye"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.COMMON
        assert c.cost == 1
        assert c.base_block == 7
        assert c.upgrade_block == 2
        assert c.base_magic == 3
        assert c.upgrade_magic == 2

    def test_prostrate(self):
        c = PROSTRATE
        assert c.id == "Prostrate"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.COMMON
        assert c.cost == 0
        assert c.base_block == 4
        assert c.base_magic == 2
        assert c.upgrade_magic == 1


# ============================================================
# WATCHER UNCOMMON ATTACKS
# ============================================================

class TestWatcherUncommonAttacks:

    def test_tantrum(self):
        c = TANTRUM
        assert c.id == "Tantrum"
        assert c.card_type == CardType.ATTACK
        assert c.rarity == CardRarity.UNCOMMON
        assert c.cost == 1
        assert c.base_damage == 3
        assert c.base_magic == 3
        assert c.upgrade_magic == 1
        assert c.shuffle_back is True

    def test_fear_no_evil(self):
        c = FEAR_NO_EVIL
        assert c.id == "FearNoEvil"
        assert c.card_type == CardType.ATTACK
        assert c.rarity == CardRarity.UNCOMMON
        assert c.cost == 1
        assert c.base_damage == 8
        assert c.upgrade_damage == 3

    def test_reach_heaven(self):
        c = REACH_HEAVEN
        assert c.id == "ReachHeaven"
        assert c.card_type == CardType.ATTACK
        assert c.rarity == CardRarity.UNCOMMON
        assert c.cost == 2
        assert c.base_damage == 10
        assert c.upgrade_damage == 5

    def test_sands_of_time(self):
        c = SANDS_OF_TIME
        assert c.id == "SandsOfTime"
        assert c.card_type == CardType.ATTACK
        assert c.rarity == CardRarity.UNCOMMON
        assert c.cost == 4
        assert c.base_damage == 20
        assert c.upgrade_damage == 6
        assert c.retain is True

    def test_signature_move(self):
        c = SIGNATURE_MOVE
        assert c.id == "SignatureMove"
        assert c.card_type == CardType.ATTACK
        assert c.rarity == CardRarity.UNCOMMON
        assert c.cost == 2
        assert c.base_damage == 30
        assert c.upgrade_damage == 10

    def test_talk_to_the_hand(self):
        c = TALK_TO_THE_HAND
        assert c.id == "TalkToTheHand"
        assert c.card_type == CardType.ATTACK
        assert c.rarity == CardRarity.UNCOMMON
        assert c.cost == 1
        assert c.base_damage == 5
        assert c.upgrade_damage == 2
        assert c.base_magic == 2
        assert c.upgrade_magic == 1
        assert c.exhaust is True

    def test_wallop(self):
        """Java: baseDamage=9, upgradeDamage(3). Python has upgrade_damage=5 which is WRONG."""
        c = WALLOP
        assert c.id == "Wallop"
        assert c.card_type == CardType.ATTACK
        assert c.rarity == CardRarity.UNCOMMON
        assert c.cost == 2
        assert c.base_damage == 9
        # MISMATCH: Java upgradeDamage=3, Python has upgrade_damage=5
        assert c.upgrade_damage == 3, f"MISMATCH: Java upgradeDamage=3, Python={c.upgrade_damage}"

    def test_weave(self):
        c = WEAVE
        assert c.id == "Weave"
        assert c.card_type == CardType.ATTACK
        assert c.rarity == CardRarity.UNCOMMON
        assert c.cost == 0
        assert c.base_damage == 4
        assert c.upgrade_damage == 2

    def test_wheel_kick(self):
        c = WHEEL_KICK
        assert c.id == "WheelKick"
        assert c.card_type == CardType.ATTACK
        assert c.rarity == CardRarity.UNCOMMON
        assert c.cost == 2
        assert c.base_damage == 15
        assert c.upgrade_damage == 5

    def test_windmill_strike(self):
        c = WINDMILL_STRIKE
        assert c.id == "WindmillStrike"
        assert c.card_type == CardType.ATTACK
        assert c.rarity == CardRarity.UNCOMMON
        assert c.cost == 2
        assert c.base_damage == 7
        assert c.upgrade_damage == 3
        assert c.retain is True

    def test_conclude(self):
        c = CONCLUDE
        assert c.id == "Conclude"
        assert c.card_type == CardType.ATTACK
        assert c.rarity == CardRarity.UNCOMMON
        assert c.target == CardTarget.ALL_ENEMY
        assert c.cost == 1
        assert c.base_damage == 12
        assert c.upgrade_damage == 4

    def test_carve_reality(self):
        c = CARVE_REALITY
        assert c.id == "CarveReality"
        assert c.card_type == CardType.ATTACK
        assert c.rarity == CardRarity.UNCOMMON
        assert c.cost == 1
        assert c.base_damage == 6
        assert c.upgrade_damage == 4


# ============================================================
# WATCHER UNCOMMON SKILLS
# ============================================================

class TestWatcherUncommonSkills:

    def test_collect(self):
        c = COLLECT
        assert c.id == "Collect"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.UNCOMMON
        assert c.cost == -1  # X cost
        assert c.exhaust is True

    def test_deceive_reality(self):
        c = DECEIVE_REALITY
        assert c.id == "DeceiveReality"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.UNCOMMON
        assert c.cost == 1
        assert c.base_block == 4
        assert c.upgrade_block == 3

    def test_indignation(self):
        """Java: target=NONE."""
        c = INDIGNATION
        assert c.id == "Indignation"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.UNCOMMON
        assert c.cost == 1
        assert c.base_magic == 3
        assert c.upgrade_magic == 2
        # MISMATCH: Java target=NONE, Python has SELF
        assert c.target == CardTarget.NONE, f"MISMATCH: Java target=NONE, Python={c.target}"

    def test_meditate(self):
        """Java: target=NONE."""
        c = MEDITATE
        assert c.id == "Meditate"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.UNCOMMON
        assert c.cost == 1
        assert c.base_magic == 1
        assert c.upgrade_magic == 1
        # MISMATCH: Java target=NONE, Python has SELF
        assert c.target == CardTarget.NONE, f"MISMATCH: Java target=NONE, Python={c.target}"

    def test_perseverance(self):
        c = PERSEVERANCE
        assert c.id == "Perseverance"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.UNCOMMON
        assert c.cost == 1
        assert c.base_block == 5
        assert c.upgrade_block == 2
        assert c.retain is True
        assert c.base_magic == 2
        assert c.upgrade_magic == 1

    def test_pray(self):
        c = PRAY
        assert c.id == "Pray"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.UNCOMMON
        assert c.cost == 1
        assert c.base_magic == 3
        assert c.upgrade_magic == 1

    def test_sanctity(self):
        c = SANCTITY
        assert c.id == "Sanctity"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.UNCOMMON
        assert c.cost == 1
        assert c.base_block == 6
        assert c.upgrade_block == 3

    def test_swivel(self):
        c = SWIVEL
        assert c.id == "Swivel"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.UNCOMMON
        assert c.cost == 2
        assert c.base_block == 8
        assert c.upgrade_block == 3

    def test_wave_of_the_hand(self):
        c = WAVE_OF_THE_HAND
        assert c.id == "WaveOfTheHand"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.UNCOMMON
        assert c.cost == 1
        assert c.base_magic == 1
        assert c.upgrade_magic == 1

    def test_simmering_fury(self):
        c = SIMMERING_FURY
        assert c.id == "Vengeance"  # Java ID
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.UNCOMMON
        assert c.target == CardTarget.NONE
        assert c.cost == 1
        assert c.base_magic == 2
        assert c.upgrade_magic == 1

    def test_worship(self):
        """Java: cost=2, baseMagicNumber=5. Upgrade grants Retain (no magic upgrade).
        Python has upgrade_magic=3 and retain=True always -- both WRONG."""
        c = WORSHIP
        assert c.id == "Worship"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.UNCOMMON
        assert c.cost == 2
        assert c.base_magic == 5
        # MISMATCH: Java upgrade gives Retain, does NOT upgrade magic number.
        # Python has upgrade_magic=3 (wrong) and retain=True always (wrong - only when upgraded).
        assert c.upgrade_magic == 0, f"MISMATCH: Java has no magic upgrade, Python={c.upgrade_magic}"

    def test_wreath_of_flame(self):
        c = WREATH_OF_FLAME
        assert c.id == "WreathOfFlame"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.UNCOMMON
        assert c.cost == 1
        assert c.base_magic == 5
        assert c.upgrade_magic == 3


# ============================================================
# WATCHER UNCOMMON/RARE POWERS
# ============================================================

class TestWatcherPowers:

    def test_battle_hymn(self):
        c = BATTLE_HYMN
        assert c.id == "BattleHymn"
        assert c.card_type == CardType.POWER
        assert c.rarity == CardRarity.UNCOMMON
        assert c.cost == 1
        assert c.base_magic == 1

    def test_establishment(self):
        """Java: rarity=RARE."""
        c = ESTABLISHMENT
        assert c.id == "Establishment"
        assert c.card_type == CardType.POWER
        # MISMATCH: Java rarity=RARE, Python has RARE (correct check)
        assert c.rarity == CardRarity.RARE, f"MISMATCH: Java rarity=RARE, Python={c.rarity}"
        assert c.cost == 1
        assert c.base_magic == 1

    def test_fasting(self):
        c = FASTING
        assert c.id == "Fasting2"  # Java ID
        assert c.card_type == CardType.POWER
        assert c.rarity == CardRarity.UNCOMMON
        assert c.cost == 2
        assert c.base_magic == 3
        assert c.upgrade_magic == 1

    def test_like_water(self):
        """Java: target=NONE."""
        c = LIKE_WATER
        assert c.id == "LikeWater"
        assert c.card_type == CardType.POWER
        assert c.rarity == CardRarity.UNCOMMON
        assert c.cost == 1
        assert c.base_magic == 5
        assert c.upgrade_magic == 2
        # MISMATCH: Java target=NONE, Python has SELF
        assert c.target == CardTarget.NONE, f"MISMATCH: Java target=NONE, Python={c.target}"

    def test_mental_fortress(self):
        c = MENTAL_FORTRESS
        assert c.id == "MentalFortress"
        assert c.card_type == CardType.POWER
        assert c.rarity == CardRarity.UNCOMMON
        assert c.cost == 1
        assert c.base_magic == 4
        assert c.upgrade_magic == 2

    def test_nirvana(self):
        c = NIRVANA
        assert c.id == "Nirvana"
        assert c.card_type == CardType.POWER
        assert c.rarity == CardRarity.UNCOMMON
        assert c.cost == 1
        assert c.base_magic == 3
        assert c.upgrade_magic == 1

    def test_rushdown(self):
        c = RUSHDOWN
        assert c.id == "Adaptation"  # Java ID
        assert c.card_type == CardType.POWER
        assert c.rarity == CardRarity.UNCOMMON
        assert c.cost == 1
        assert c.upgrade_cost == 0

    def test_study(self):
        c = STUDY
        assert c.id == "Study"
        assert c.card_type == CardType.POWER
        assert c.rarity == CardRarity.UNCOMMON
        assert c.cost == 2
        assert c.upgrade_cost == 1

    def test_foresight(self):
        """Java: target=NONE."""
        c = FORESIGHT
        assert c.id == "Wireheading"  # Java ID
        assert c.card_type == CardType.POWER
        assert c.rarity == CardRarity.UNCOMMON
        assert c.cost == 1
        assert c.base_magic == 3
        assert c.upgrade_magic == 1
        # MISMATCH: Java target=NONE, Python has SELF
        assert c.target == CardTarget.NONE, f"MISMATCH: Java target=NONE, Python={c.target}"

    def test_deva_form(self):
        c = DEVA_FORM
        assert c.id == "DevaForm"
        assert c.card_type == CardType.POWER
        assert c.rarity == CardRarity.RARE
        assert c.cost == 3
        assert c.ethereal is True
        # Note: Java upgrade removes ethereal. Python doesn't model upgrade removing flags.

    def test_devotion(self):
        """Java: rarity=RARE, target=NONE."""
        c = DEVOTION
        assert c.id == "Devotion"
        assert c.card_type == CardType.POWER
        assert c.rarity == CardRarity.RARE
        assert c.cost == 1
        assert c.base_magic == 2
        assert c.upgrade_magic == 1
        # MISMATCH: Java target=NONE, Python has SELF
        assert c.target == CardTarget.NONE, f"MISMATCH: Java target=NONE, Python={c.target}"

    def test_master_reality(self):
        c = MASTER_REALITY
        assert c.id == "MasterReality"
        assert c.card_type == CardType.POWER
        assert c.rarity == CardRarity.RARE
        assert c.cost == 1
        assert c.upgrade_cost == 0


# ============================================================
# WATCHER RARE ATTACKS
# ============================================================

class TestWatcherRareAttacks:

    def test_brilliance(self):
        c = BRILLIANCE
        assert c.id == "Brilliance"
        assert c.card_type == CardType.ATTACK
        assert c.rarity == CardRarity.RARE
        assert c.cost == 1
        assert c.base_damage == 12
        assert c.upgrade_damage == 4

    def test_judgment(self):
        """Java: type=SKILL, target=ENEMY, cost=1.
        Python has it as ATTACK which is WRONG. It's a SKILL in Java."""
        c = JUDGMENT
        assert c.id == "Judgement"
        # MISMATCH: Java type=SKILL, Python has ATTACK
        assert c.card_type == CardType.SKILL, f"MISMATCH: Java type=SKILL, Python={c.card_type}"
        assert c.rarity == CardRarity.RARE
        assert c.cost == 1
        assert c.base_magic == 30
        assert c.upgrade_magic == 10

    def test_lesson_learned(self):
        c = LESSON_LEARNED
        assert c.id == "LessonLearned"
        assert c.card_type == CardType.ATTACK
        assert c.rarity == CardRarity.RARE
        assert c.cost == 2
        assert c.base_damage == 10
        assert c.upgrade_damage == 3
        assert c.exhaust is True

    def test_ragnarok(self):
        c = RAGNAROK
        assert c.id == "Ragnarok"
        assert c.card_type == CardType.ATTACK
        assert c.rarity == CardRarity.RARE
        assert c.target == CardTarget.ALL_ENEMY
        assert c.cost == 3
        assert c.base_damage == 5
        assert c.upgrade_damage == 1
        assert c.base_magic == 5
        assert c.upgrade_magic == 1


# ============================================================
# WATCHER RARE SKILLS
# ============================================================

class TestWatcherRareSkills:

    def test_deus_ex_machina(self):
        c = DEUS_EX_MACHINA
        assert c.id == "DeusExMachina"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.RARE
        assert c.cost == -2  # Unplayable
        assert c.exhaust is True
        assert c.base_magic == 2
        assert c.upgrade_magic == 1

    def test_alpha(self):
        """Java: cost=1, target=NONE, no cost change. Upgrade grants Innate.
        Python has upgrade_cost=0 (WRONG) and innate=True always (WRONG)."""
        c = ALPHA
        assert c.id == "Alpha"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.RARE
        assert c.cost == 1
        assert c.exhaust is True
        # MISMATCH: Java target=NONE, Python may have different
        assert c.target == CardTarget.NONE, f"MISMATCH: Java target=NONE, Python={c.target}"
        # MISMATCH: Java does NOT change cost on upgrade. Python has upgrade_cost=0.
        assert c.upgrade_cost is None, f"MISMATCH: Java no cost upgrade, Python upgrade_cost={c.upgrade_cost}"
        # MISMATCH: Innate only when upgraded, not base.
        assert c.innate is False, f"MISMATCH: Java innate only on upgrade, Python innate={c.innate}"

    def test_blasphemy(self):
        """Java: cost=1, exhaust=true. Upgrade grants Retain (no cost change).
        Python has upgrade_cost=0 (WRONG) and retain=True always (WRONG)."""
        c = BLASPHEMY
        assert c.id == "Blasphemy"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.RARE
        assert c.cost == 1
        assert c.exhaust is True
        # MISMATCH: Java does NOT change cost on upgrade. Python has upgrade_cost=0.
        assert c.upgrade_cost is None, f"MISMATCH: Java no cost upgrade, Python upgrade_cost={c.upgrade_cost}"
        # MISMATCH: Retain only when upgraded in Java. Python has retain=True base.
        assert c.retain is False, f"MISMATCH: Java retain only on upgrade, Python retain={c.retain}"

    def test_conjure_blade(self):
        """Java: cost=-1 (X cost). Python has cost=0 (WRONG)."""
        c = CONJURE_BLADE
        assert c.id == "ConjureBlade"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.RARE
        # MISMATCH: Java cost=-1 (X cost), Python has cost=0
        assert c.cost == -1, f"MISMATCH: Java cost=-1 (X), Python cost={c.cost}"
        assert c.exhaust is True

    def test_foreign_influence(self):
        """Java: target=NONE."""
        c = FOREIGN_INFLUENCE
        assert c.id == "ForeignInfluence"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.UNCOMMON
        assert c.cost == 0
        assert c.exhaust is True
        # MISMATCH: Java target=NONE, Python has SELF
        assert c.target == CardTarget.NONE, f"MISMATCH: Java target=NONE, Python={c.target}"

    def test_omniscience(self):
        """Java: target=NONE."""
        c = OMNISCIENCE
        assert c.id == "Omniscience"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.RARE
        assert c.cost == 4
        assert c.upgrade_cost == 3
        assert c.exhaust is True
        # MISMATCH: Java target=NONE, Python has SELF
        assert c.target == CardTarget.NONE, f"MISMATCH: Java target=NONE, Python={c.target}"

    def test_scrawl(self):
        """Java: target=NONE."""
        c = SCRAWL
        assert c.id == "Scrawl"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.RARE
        assert c.cost == 1
        assert c.upgrade_cost == 0
        assert c.exhaust is True
        # MISMATCH: Java target=NONE, Python has SELF
        assert c.target == CardTarget.NONE, f"MISMATCH: Java target=NONE, Python={c.target}"

    def test_spirit_shield(self):
        c = SPIRIT_SHIELD
        assert c.id == "SpiritShield"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.RARE
        assert c.cost == 2
        assert c.base_magic == 3
        assert c.upgrade_magic == 1

    def test_vault(self):
        """Java: target=ALL."""
        c = VAULT
        assert c.id == "Vault"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.RARE
        assert c.cost == 3
        assert c.upgrade_cost == 2
        assert c.exhaust is True
        # MISMATCH: Java target=ALL, Python has SELF
        assert c.target == CardTarget.ALL, f"MISMATCH: Java target=ALL, Python={c.target}"

    def test_wish(self):
        """Java: target=NONE, has baseDamage=3, baseBlock=6, baseMagicNumber=25.
        Python is missing damage/block fields and has wrong target."""
        c = WISH
        assert c.id == "Wish"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.RARE
        assert c.cost == 3
        assert c.exhaust is True
        # MISMATCH: Java target=NONE, Python has SELF
        assert c.target == CardTarget.NONE, f"MISMATCH: Java target=NONE, Python={c.target}"
        # Java has baseDamage=3, baseBlock=6, baseMagicNumber=25
        # These are used by the sub-option cards (BecomeAlmighty, FameAndFortune, LiveForever)
        # Python doesn't set these, only upgrade_magic=1 which is also wrong (Java upgradeMagicNumber=5)


# ============================================================
# TEMP/SPECIAL CARDS
# ============================================================

class TestTempCards:

    def test_miracle(self):
        c = MIRACLE
        assert c.id == "Miracle"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.SPECIAL
        assert c.cost == 0
        assert c.retain is True
        assert c.exhaust is True

    def test_insight(self):
        c = INSIGHT
        assert c.id == "Insight"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.SPECIAL
        assert c.cost == 0
        assert c.retain is True
        assert c.exhaust is True
        assert c.base_magic == 2
        assert c.upgrade_magic == 1

    def test_smite(self):
        c = SMITE
        assert c.id == "Smite"
        assert c.card_type == CardType.ATTACK
        assert c.rarity == CardRarity.SPECIAL
        assert c.cost == 1
        assert c.base_damage == 12
        assert c.upgrade_damage == 4
        assert c.retain is True
        assert c.exhaust is True

    def test_safety(self):
        c = SAFETY
        assert c.id == "Safety"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.SPECIAL
        assert c.cost == 1
        assert c.base_block == 12
        assert c.upgrade_block == 4
        assert c.retain is True
        assert c.exhaust is True

    def test_through_violence(self):
        c = THROUGH_VIOLENCE
        assert c.id == "ThroughViolence"
        assert c.card_type == CardType.ATTACK
        assert c.rarity == CardRarity.SPECIAL
        assert c.cost == 0
        assert c.base_damage == 20
        assert c.upgrade_damage == 10
        assert c.retain is True
        assert c.exhaust is True

    def test_expunger(self):
        c = EXPUNGER
        assert c.id == "Expunger"
        assert c.card_type == CardType.ATTACK
        assert c.rarity == CardRarity.SPECIAL
        assert c.cost == 1
        assert c.base_damage == 9

    def test_beta(self):
        c = BETA
        assert c.id == "Beta"
        assert c.card_type == CardType.SKILL
        assert c.rarity == CardRarity.SPECIAL
        assert c.cost == 2
        assert c.upgrade_cost == 1
        assert c.exhaust is True

    def test_omega(self):
        c = OMEGA
        assert c.id == "Omega"
        assert c.card_type == CardType.POWER
        assert c.rarity == CardRarity.SPECIAL
        assert c.cost == 3
        # Java: baseMagicNumber=50, upgradeMagicNumber(10)
        # Python doesn't set base_magic for Omega


# ============================================================
# CURSE CARDS
# ============================================================

class TestCurseCards:

    def test_ascenders_bane(self):
        c = ASCENDERS_BANE
        assert c.id == "AscendersBane"
        assert c.card_type == CardType.CURSE
        assert c.color == CardColor.CURSE
        assert c.cost == -2
        assert c.ethereal is True

    def test_clumsy(self):
        c = CLUMSY
        assert c.id == "Clumsy"
        assert c.card_type == CardType.CURSE
        assert c.cost == -2
        assert c.ethereal is True

    def test_curse_of_the_bell(self):
        c = CURSE_OF_THE_BELL
        assert c.id == "CurseOfTheBell"
        assert c.card_type == CardType.CURSE
        assert c.cost == -2

    def test_decay(self):
        c = DECAY
        assert c.id == "Decay"
        assert c.card_type == CardType.CURSE
        assert c.cost == -2

    def test_doubt(self):
        c = DOUBT
        assert c.id == "Doubt"
        assert c.card_type == CardType.CURSE
        assert c.cost == -2

    def test_injury(self):
        c = INJURY
        assert c.id == "Injury"
        assert c.card_type == CardType.CURSE
        assert c.cost == -2

    def test_necronomicurse(self):
        c = NECRONOMICURSE
        assert c.id == "Necronomicurse"
        assert c.card_type == CardType.CURSE
        assert c.cost == -2

    def test_normality(self):
        c = NORMALITY
        assert c.id == "Normality"
        assert c.card_type == CardType.CURSE
        assert c.cost == -2

    def test_pain(self):
        c = PAIN
        assert c.id == "Pain"
        assert c.card_type == CardType.CURSE
        assert c.cost == -2

    def test_parasite(self):
        c = PARASITE
        assert c.id == "Parasite"
        assert c.card_type == CardType.CURSE
        assert c.cost == -2

    def test_pride(self):
        c = PRIDE
        assert c.id == "Pride"
        assert c.card_type == CardType.CURSE
        assert c.cost == 1
        assert c.innate is True
        assert c.exhaust is True

    def test_regret(self):
        c = REGRET
        assert c.id == "Regret"
        assert c.card_type == CardType.CURSE
        assert c.cost == -2

    def test_shame(self):
        c = SHAME
        assert c.id == "Shame"
        assert c.card_type == CardType.CURSE
        assert c.cost == -2

    def test_writhe(self):
        c = WRITHE
        assert c.id == "Writhe"
        assert c.card_type == CardType.CURSE
        assert c.cost == -2
        assert c.innate is True


# ============================================================
# STATUS CARDS
# ============================================================

class TestStatusCards:

    def test_burn(self):
        c = BURN
        assert c.id == "Burn"
        assert c.card_type == CardType.STATUS
        assert c.cost == -2
        assert c.base_magic == 2
        assert c.upgrade_magic == 2

    def test_dazed(self):
        c = DAZED
        assert c.id == "Dazed"
        assert c.card_type == CardType.STATUS
        assert c.cost == -2
        assert c.ethereal is True

    def test_slimed(self):
        c = SLIMED
        assert c.id == "Slimed"
        assert c.card_type == CardType.STATUS
        assert c.cost == 1
        assert c.exhaust is True

    def test_void(self):
        c = VOID
        assert c.id == "Void"
        assert c.card_type == CardType.STATUS
        assert c.cost == -2
        assert c.ethereal is True

    def test_wound(self):
        c = WOUND
        assert c.id == "Wound"
        assert c.card_type == CardType.STATUS
        assert c.cost == -2


# ============================================================
# REGISTRY COMPLETENESS
# ============================================================

class TestRegistryCompleteness:
    """Verify all expected cards exist in their registries."""

    EXPECTED_WATCHER_IDS = [
        "Strike_P", "Defend_P", "Eruption", "Vigilance", "Miracle",
        "BowlingBash", "CutThroughFate", "EmptyFist", "FlurryOfBlows",
        "FlyingSleeves", "FollowUp", "Halt", "JustLucky", "PathToVictory",
        "SashWhip", "ClearTheMind", "Crescendo", "Consecrate", "CrushJoints",
        "EmptyBody", "EmptyMind", "Evaluate", "InnerPeace", "Protect",
        "ThirdEye", "Prostrate",
        "Tantrum", "FearNoEvil", "ReachHeaven", "SandsOfTime",
        "SignatureMove", "TalkToTheHand", "Wallop", "Weave", "WheelKick",
        "WindmillStrike", "Conclude", "CarveReality",
        "Collect", "DeceiveReality", "Wireheading", "Indignation",
        "Meditate", "Perseverance", "Pray", "Sanctity", "Swivel",
        "Vengeance", "WaveOfTheHand", "Worship", "WreathOfFlame",
        "BattleHymn", "Establishment", "LikeWater", "MentalFortress",
        "Nirvana", "Adaptation", "Study",
        "Brilliance", "Judgement", "LessonLearned", "Ragnarok",
        "DeusExMachina", "Alpha", "Blasphemy", "ConjureBlade",
        "ForeignInfluence", "Omniscience", "Scrawl", "SpiritShield",
        "Vault", "Wish",
        "DevaForm", "Devotion", "Fasting2", "MasterReality",
        "Insight", "Smite", "Safety", "ThroughViolence", "Expunger",
        "Beta", "Omega",
    ]

    EXPECTED_CURSE_IDS = [
        "AscendersBane", "Clumsy", "CurseOfTheBell", "Decay", "Doubt",
        "Injury", "Necronomicurse", "Normality", "Pain", "Parasite",
        "Pride", "Regret", "Shame", "Writhe",
    ]

    EXPECTED_STATUS_IDS = [
        "Burn", "Dazed", "Slimed", "Void", "Wound",
    ]

    def test_watcher_registry_complete(self):
        for card_id in self.EXPECTED_WATCHER_IDS:
            assert card_id in WATCHER_CARDS, f"Missing Watcher card: {card_id}"

    def test_curse_registry_complete(self):
        for card_id in self.EXPECTED_CURSE_IDS:
            assert card_id in CURSE_CARDS, f"Missing Curse card: {card_id}"

    def test_status_registry_complete(self):
        for card_id in self.EXPECTED_STATUS_IDS:
            assert card_id in STATUS_CARDS, f"Missing Status card: {card_id}"

    def test_missing_watcher_cards(self):
        """Cards that exist in Java but are NOT in Python at all."""
        # Discipline (ID="Discipline") - Power, Rare, cost=2, upgradeBaseCost(1)
        assert "Discipline" not in WATCHER_CARDS, "Discipline is missing from Python (expected)"
        # Unraveling (ID="Unraveling") - Skill, Rare, cost=2, upgradeBaseCost(1)
        assert "Unraveling" not in WATCHER_CARDS, "Unraveling is missing from Python (expected)"


# ============================================================
# SUMMARY OF ALL DISCREPANCIES
# ============================================================

class TestDiscrepancySummary:
    """
    Consolidated list of all Java vs Python mismatches found in this audit.
    Each test here documents a specific bug. When fixed, the corresponding
    test in the card-specific classes above should also pass.

    CRITICAL BUGS (affect gameplay):
    1. Tranquility: base cost=0 should be 1 (upgrade to 0)
    2. Crescendo: base cost=0 should be 1 (upgrade to 0)
    3. Wallop: upgrade_damage=5 should be 3
    4. Judgment: card_type=ATTACK should be SKILL
    5. Blasphemy: upgrade_cost=0 wrong (no cost change), retain=True wrong (only on upgrade)
    6. Alpha: upgrade_cost=0 wrong (no cost change), innate=True wrong (only on upgrade)
    7. ConjureBlade: cost=0 should be -1 (X cost)
    8. Worship: upgrade_magic=3 wrong (no magic upgrade), retain=True wrong (only on upgrade)

    TARGET MISMATCHES (many powers/skills use SELF instead of NONE):
    9.  Indignation: target=SELF should be NONE
    10. Meditate: target=SELF should be NONE
    11. LikeWater: target=SELF should be NONE
    12. Foresight: target=SELF should be NONE
    13. Devotion: target=SELF should be NONE
    14. ForeignInfluence: target=SELF should be NONE
    15. Omniscience: target=SELF should be NONE
    16. Scrawl: target=SELF should be NONE
    17. Vault: target=SELF should be ALL
    18. Wish: target=SELF should be NONE

    MISSING CARDS:
    19. Discipline (purple Power, ID="Discipline")
    20. Unraveling (purple Skill, ID="Unraveling")

    UPGRADE FLAG MODELING GAPS:
    - DevaForm: upgrade removes ethereal (not modeled)
    - Alpha: upgrade adds innate (modeled as always innate)
    - Blasphemy: upgrade adds retain (modeled as always retain)
    - Worship: upgrade adds retain (modeled as always retain)
    - Crescendo: upgrade should reduce cost (modeled as base cost 0)
    - Tranquility: upgrade should reduce cost (modeled as base cost 0)
    """

    def test_total_discrepancy_count(self):
        """This test exists to document the total number of discrepancies found."""
        # 8 critical stat bugs + 10 target mismatches + 2 missing cards = 20 total
        discrepancies = 20
        assert discrepancies > 0, "Audit found discrepancies that need fixing"
