use std::collections::HashMap;
use super::CardDef;

mod anger;
mod armaments;
mod barricade;
mod bash;
mod battle_trance;
mod berserk;
mod blood_for_blood;
mod bloodletting;
mod bludgeon;
mod body_slam;
mod brutality;
mod burning_pact;
mod carnage;
mod clash;
mod cleave;
mod clothesline;
mod combust;
mod corruption;
mod dark_embrace;
mod demon_form;
mod disarm;
mod double_tap;
mod dropkick;
mod dual_wield;
mod entrench;
mod evolve;
mod exhume;
mod feed;
mod feel_no_pain;
mod fiend_fire;
mod fire_breathing;
mod flame_barrier;
mod flex;
mod ghostly_armor;
mod havoc;
mod headbutt;
mod heavy_blade;
mod hemokinesis;
mod immolate;
mod impervious;
mod infernal_blade;
mod inflame;
mod intimidate;
mod iron_wave;
mod juggernaut;
mod limit_break;
mod metallicize;
mod offering;
mod perfected_strike;
mod pommel_strike;
mod power_through;
mod pummel;
mod rage;
mod rampage;
mod reaper;
mod reckless_charge;
mod rupture;
mod searing_blow;
mod second_wind;
mod seeing_red;
mod sentinel;
mod sever_soul;
mod shockwave;
mod shrug_it_off;
mod spot_weakness;
mod sword_boomerang;
mod thunderclap;
mod true_grit;
mod twin_strike;
mod uppercut;
mod warcry;
mod whirlwind;
mod wild_strike;

pub fn register_ironclad(cards: &mut HashMap<&'static str, CardDef>) {
    anger::register(cards);
    armaments::register(cards);
    barricade::register(cards);
    bash::register(cards);
    battle_trance::register(cards);
    berserk::register(cards);
    blood_for_blood::register(cards);
    bloodletting::register(cards);
    bludgeon::register(cards);
    body_slam::register(cards);
    brutality::register(cards);
    burning_pact::register(cards);
    carnage::register(cards);
    clash::register(cards);
    cleave::register(cards);
    clothesline::register(cards);
    combust::register(cards);
    corruption::register(cards);
    dark_embrace::register(cards);
    demon_form::register(cards);
    disarm::register(cards);
    double_tap::register(cards);
    dropkick::register(cards);
    dual_wield::register(cards);
    entrench::register(cards);
    evolve::register(cards);
    exhume::register(cards);
    feed::register(cards);
    feel_no_pain::register(cards);
    fiend_fire::register(cards);
    fire_breathing::register(cards);
    flame_barrier::register(cards);
    flex::register(cards);
    ghostly_armor::register(cards);
    havoc::register(cards);
    headbutt::register(cards);
    heavy_blade::register(cards);
    hemokinesis::register(cards);
    immolate::register(cards);
    impervious::register(cards);
    infernal_blade::register(cards);
    inflame::register(cards);
    intimidate::register(cards);
    iron_wave::register(cards);
    juggernaut::register(cards);
    limit_break::register(cards);
    metallicize::register(cards);
    offering::register(cards);
    perfected_strike::register(cards);
    pommel_strike::register(cards);
    power_through::register(cards);
    pummel::register(cards);
    rage::register(cards);
    rampage::register(cards);
    reaper::register(cards);
    reckless_charge::register(cards);
    rupture::register(cards);
    searing_blow::register(cards);
    second_wind::register(cards);
    seeing_red::register(cards);
    sentinel::register(cards);
    sever_soul::register(cards);
    shockwave::register(cards);
    shrug_it_off::register(cards);
    spot_weakness::register(cards);
    sword_boomerang::register(cards);
    thunderclap::register(cards);
    true_grit::register(cards);
    twin_strike::register(cards);
    uppercut::register(cards);
    warcry::register(cards);
    whirlwind::register(cards);
    wild_strike::register(cards);
}
