use std::collections::HashMap;
use super::CardSpec as CardDef;

mod apotheosis;
mod bandage_up;
mod bite;
mod blind;
mod chrysalis;
mod dark_shackles;
mod deep_breath;
mod defend_r;
mod discovery;
mod dramatic_entrance;
mod enlightenment;
mod finesse;
mod flash_of_steel;
mod forethought;
mod ghostly;
mod good_instincts;
mod handofgreed;
mod impatience;
mod jack_of_all_trades;
mod jax;
mod madness;
mod magnetism;
mod master_of_strategy;
mod mayhem;
mod metamorphosis;
mod mind_blast;
mod panacea;
mod panache;
mod panicbutton;
mod purity;
mod ritualdagger;
mod sadistic_nature;
mod secret_technique;
mod secret_weapon;
mod strike_r;
mod swift_strike;
mod the_bomb;
mod thinking_ahead;
mod transmutation;
mod trip;
mod violence;

pub fn register_colorless(cards: &mut HashMap<&'static str, CardDef>) {
    apotheosis::register(cards);
    bandage_up::register(cards);
    bite::register(cards);
    blind::register(cards);
    chrysalis::register(cards);
    dark_shackles::register(cards);
    deep_breath::register(cards);
    defend_r::register(cards);
    discovery::register(cards);
    dramatic_entrance::register(cards);
    enlightenment::register(cards);
    finesse::register(cards);
    flash_of_steel::register(cards);
    forethought::register(cards);
    ghostly::register(cards);
    good_instincts::register(cards);
    handofgreed::register(cards);
    impatience::register(cards);
    jack_of_all_trades::register(cards);
    jax::register(cards);
    madness::register(cards);
    magnetism::register(cards);
    master_of_strategy::register(cards);
    mayhem::register(cards);
    metamorphosis::register(cards);
    mind_blast::register(cards);
    panacea::register(cards);
    panache::register(cards);
    panicbutton::register(cards);
    purity::register(cards);
    ritualdagger::register(cards);
    sadistic_nature::register(cards);
    secret_technique::register(cards);
    secret_weapon::register(cards);
    strike_r::register(cards);
    swift_strike::register(cards);
    the_bomb::register(cards);
    thinking_ahead::register(cards);
    transmutation::register(cards);
    trip::register(cards);
    violence::register(cards);
}
