use std::collections::HashMap;
use super::CardDef;

mod aggregate;
mod all_for_one;
mod amplify;
mod auto_shields;
mod ball_lightning;
mod barrage;
mod beam_cell;
mod biased_cognition;
mod blizzard;
mod bootsequence;
mod buffer;
mod capacitor;
mod chaos;
mod chill;
mod cold_snap;
mod compile_driver;
mod conserve_battery;
mod consume;
mod coolheaded;
mod core_surge;
mod creative_ai;
mod darkness;
mod defend_b;
mod defragment;
mod doom_and_gloom;
mod double_energy;
mod dualcast;
mod echo_form;
mod electrodynamics;
mod fission;
mod force_field;
mod ftl;
mod fusion;
mod gash;
mod genetic_algorithm;
mod glacier;
mod go_for_the_eyes;
mod heatsinks;
mod hello_world;
mod hologram;
mod hyperbeam;
mod impulse;
mod leap;
mod lockon;
mod loop_card;
mod machine_learning;
mod melter;
mod meteor_strike;
mod multi_cast;
mod rainbow;
mod reboot;
mod rebound;
mod recycle;
mod redo;
mod reinforced_body;
mod reprogram;
mod rip_and_tear;
mod scrape;
mod seek;
mod self_repair;
mod skim;
mod stack;
mod static_discharge;
mod steam;
mod steam_power;
mod storm;
mod streamline;
mod strike_b;
mod sunder;
mod sweeping_beam;
mod tempest;
mod thunder_strike;
mod turbo;
mod undo;
mod white_noise;
mod zap;

pub fn register_defect(cards: &mut HashMap<&'static str, CardDef>) {
    aggregate::register(cards);
    all_for_one::register(cards);
    amplify::register(cards);
    auto_shields::register(cards);
    ball_lightning::register(cards);
    barrage::register(cards);
    beam_cell::register(cards);
    biased_cognition::register(cards);
    blizzard::register(cards);
    bootsequence::register(cards);
    buffer::register(cards);
    capacitor::register(cards);
    chaos::register(cards);
    chill::register(cards);
    cold_snap::register(cards);
    compile_driver::register(cards);
    conserve_battery::register(cards);
    consume::register(cards);
    coolheaded::register(cards);
    core_surge::register(cards);
    creative_ai::register(cards);
    darkness::register(cards);
    defend_b::register(cards);
    defragment::register(cards);
    doom_and_gloom::register(cards);
    double_energy::register(cards);
    dualcast::register(cards);
    echo_form::register(cards);
    electrodynamics::register(cards);
    fission::register(cards);
    force_field::register(cards);
    ftl::register(cards);
    fusion::register(cards);
    gash::register(cards);
    genetic_algorithm::register(cards);
    glacier::register(cards);
    go_for_the_eyes::register(cards);
    heatsinks::register(cards);
    hello_world::register(cards);
    hologram::register(cards);
    hyperbeam::register(cards);
    impulse::register(cards);
    leap::register(cards);
    lockon::register(cards);
    loop_card::register(cards);
    machine_learning::register(cards);
    melter::register(cards);
    meteor_strike::register(cards);
    multi_cast::register(cards);
    rainbow::register(cards);
    reboot::register(cards);
    rebound::register(cards);
    recycle::register(cards);
    redo::register(cards);
    reinforced_body::register(cards);
    reprogram::register(cards);
    rip_and_tear::register(cards);
    scrape::register(cards);
    seek::register(cards);
    self_repair::register(cards);
    skim::register(cards);
    stack::register(cards);
    static_discharge::register(cards);
    steam::register(cards);
    steam_power::register(cards);
    storm::register(cards);
    streamline::register(cards);
    strike_b::register(cards);
    sunder::register(cards);
    sweeping_beam::register(cards);
    tempest::register(cards);
    thunder_strike::register(cards);
    turbo::register(cards);
    undo::register(cards);
    white_noise::register(cards);
    zap::register(cards);
}
