use std::collections::HashMap;
use super::CardSpec as CardDef;

mod a_thousand_cuts;
mod accuracy;
mod acrobatics;
mod adrenaline;
mod after_image;
mod alchemize;
mod all_out_attack;
mod backflip;
mod backstab;
mod bane;
mod blade_dance;
mod blur;
mod bouncing_flask;
mod bullet_time;
mod burst;
mod calculated_gamble;
mod caltrops;
mod catalyst;
mod choke;
mod cloak_and_dagger;
mod concentrate;
mod corpse_explosion;
mod crippling_cloud;
mod dagger_spray;
mod dagger_throw;
mod dash;
mod deadly_poison;
mod defend_g;
mod deflect;
mod die_die_die;
mod distraction;
mod dodge_and_roll;
mod doppelganger;
mod endless_agony;
mod envenom;
mod escape_plan;
mod eviscerate;
mod expertise;
mod finisher;
mod flechettes;
mod flying_knee;
mod footwork;
mod glass_knife;
mod grand_finale;
mod heel_hook;
mod infinite_blades;
mod leg_sweep;
mod malaise;
mod masterful_stab;
mod neutralize;
mod nightmare;
mod noxious_fumes;
mod outmaneuver;
mod phantasmal_killer;
mod piercing_wail;
mod poisoned_stab;
mod predator;
mod prepared;
mod quick_slash;
mod reflex;
mod riddle_with_holes;
mod setup;
mod shiv;
mod skewer;
mod slice;
mod sneaky_strike;
mod storm_of_steel;
mod strike_g;
mod sucker_punch;
mod survivor;
mod tactician;
mod terror;
mod tools_of_the_trade;
mod unload;
mod well_laid_plans;
mod wraith_form;

pub fn register_silent(cards: &mut HashMap<&'static str, CardDef>) {
    a_thousand_cuts::register(cards);
    accuracy::register(cards);
    acrobatics::register(cards);
    adrenaline::register(cards);
    after_image::register(cards);
    alchemize::register(cards);
    all_out_attack::register(cards);
    backflip::register(cards);
    backstab::register(cards);
    bane::register(cards);
    blade_dance::register(cards);
    blur::register(cards);
    bouncing_flask::register(cards);
    bullet_time::register(cards);
    burst::register(cards);
    calculated_gamble::register(cards);
    caltrops::register(cards);
    catalyst::register(cards);
    choke::register(cards);
    cloak_and_dagger::register(cards);
    concentrate::register(cards);
    corpse_explosion::register(cards);
    crippling_cloud::register(cards);
    dagger_spray::register(cards);
    dagger_throw::register(cards);
    dash::register(cards);
    deadly_poison::register(cards);
    defend_g::register(cards);
    deflect::register(cards);
    die_die_die::register(cards);
    distraction::register(cards);
    dodge_and_roll::register(cards);
    doppelganger::register(cards);
    endless_agony::register(cards);
    envenom::register(cards);
    escape_plan::register(cards);
    eviscerate::register(cards);
    expertise::register(cards);
    finisher::register(cards);
    flechettes::register(cards);
    flying_knee::register(cards);
    footwork::register(cards);
    glass_knife::register(cards);
    grand_finale::register(cards);
    heel_hook::register(cards);
    infinite_blades::register(cards);
    leg_sweep::register(cards);
    malaise::register(cards);
    masterful_stab::register(cards);
    neutralize::register(cards);
    nightmare::register(cards);
    noxious_fumes::register(cards);
    outmaneuver::register(cards);
    phantasmal_killer::register(cards);
    piercing_wail::register(cards);
    poisoned_stab::register(cards);
    predator::register(cards);
    prepared::register(cards);
    quick_slash::register(cards);
    reflex::register(cards);
    riddle_with_holes::register(cards);
    setup::register(cards);
    shiv::register(cards);
    skewer::register(cards);
    slice::register(cards);
    sneaky_strike::register(cards);
    storm_of_steel::register(cards);
    strike_g::register(cards);
    sucker_punch::register(cards);
    survivor::register(cards);
    tactician::register(cards);
    terror::register(cards);
    tools_of_the_trade::register(cards);
    unload::register(cards);
    well_laid_plans::register(cards);
    wraith_form::register(cards);
}
